// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase project.
///
/// A default instance has been configured for each platform supported by FlutterFire:
/// `web`, `android`, `ios`, and `macos`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this project by running `flutterfire configure`',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this project by running `flutterfire configure`',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this project by running `flutterfire configure`',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this project by running `flutterfire configure`',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCniJX_rNqgRDIWuLD0tLs1anJYASQw3FM',
    appId: '1:456209894195:android:df5121a7737b8005f24c46',
    messagingSenderId: '456209894195',
    projectId: 'findipro-7fe13',
    storageBucket: 'findipro-7fe13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCniJX_rNqgRDIWuLD0tLs1anJYASQw3FM',
    appId: '1:456209894195:ios:d8f2b3c4a1e0f9g8h7i6j5',
    messagingSenderId: '456209894195',
    projectId: 'findipro-7fe13',
    storageBucket: 'findipro-7fe13.firebasestorage.app',
    iosBundleId: 'com.example.findipro',
  );
}