import 'package:flutter/material.dart';
import 'package:findipro/theme/app_theme.dart';
import 'package:findipro/screens/main_screen.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This will be generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const FindiProApp());
}

class FindiProApp extends StatelessWidget {
  const FindiProApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'FindiPro',
      theme: AppTheme.theme,
      home: const MainScreen(),
      debugShowCheckedModeBanner: false,
    );
  }
}