class AppLanguage {
  final String code;
  final String name;
  final String nativeName;
  final String flag;

  const AppLanguage({
    required this.code,
    required this.name,
    required this.nativeName,
    required this.flag,
  });
}

class AppStrings {
  static const List<AppLanguage> supportedLanguages = [
    AppLanguage(code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧'),
    AppLanguage(code: 'lg', name: 'Luganda', nativeName: 'Oluganda', flag: '🇺🇬'),
    AppLanguage(code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', flag: '🇹🇿'),
    AppLanguage(code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷'),
    AppLanguage(code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸'),
    AppLanguage(code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇦🇪'),
  ];

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'app_name': 'FindiPro',
      'tagline': 'Find trusted professionals near you',
      'explore': 'Explore',
      'categories': 'Categories',
      'bookings': 'Bookings',
      'messages': 'Messages',
      'profile': 'Profile',
      'dashboard': 'Dashboard',
      'search_hint': 'Search services, plumbers, electricians...',
      'find_services': 'Find Trusted Services',
      'top_categories': 'Popular Categories',
      'featured_providers': 'Verified & Top Rated Providers',
      'see_all': 'See all',
      'view_profile': 'View Profile',
      'book_now': 'Book Service',
      'call_now': 'Call',
      'chat_now': 'Chat',
      'select_language': 'Select Language',
      'change_language': 'Change App Language',
      'lifetime_premium': 'Limited Promotional Trial',
      'verified_badge': 'Verified Pro',
      'save': 'Save',
      'cancel': 'Cancel',
      'apply': 'Apply',
      'login': 'Log In',
      'signup': 'Create Account',
      'welcome_back': 'Welcome Back',
      'become_provider': 'Become a Service Provider',
      'give_feedback': 'Share Feedback & Feature Requests',
      'settings': 'Settings',
      'rate_app': 'Rate & Review',
      'privacy_policy': 'Privacy Policy & Terms',
      'logout': 'Sign Out',
    },
    'lg': {
      'app_name': 'FindiPro',
      'tagline': 'Funa abakozi abesigika abakuli okumpi',
      'explore': 'Noonya',
      'categories': 'Ebika',
      'bookings': 'Emirimu',
      'messages': 'Obubaka',
      'profile': 'Ebikukwatako',
      'dashboard': 'Ddashiboodi',
      'search_hint': 'Noonya plamba, kalipentala, lekisina...',
      'find_services': 'Funa Abakozi Abalungi',
      'top_categories': 'Ebika Ebikyasinze',
      'featured_providers': 'Abakozi Abalondebwa',
      'see_all': 'Laba byonna',
      'view_profile': 'Laba Ebimukwatako',
      'book_now': 'Funa Omuweereza',
      'call_now': 'Kuba Essimu',
      'chat_now': 'Wuliziganya',
      'select_language': 'Londa Olulimi',
      'change_language': 'Kyusa Olulimi lw\'App',
      'lifetime_premium': 'Okugezesa kwa Akaseera',
      'verified_badge': 'Akakasiddwa',
      'save': 'Kaza',
      'cancel': 'Sazaamu',
      'apply': 'Kozesa',
      'login': 'Yingira',
      'signup': 'Ggulawo Akaawunti',
      'welcome_back': 'Tukwanirizza Nnyo',
      'become_provider': 'Fuuka Omuweereza w\'Emirimu',
      'give_feedback': 'Wa Ebirowoozo & Okusaba',
      'settings': 'Enteekateeka',
      'rate_app': 'Tuwa Obubonero',
      'privacy_policy': 'Ebiragiro n\'Ebyokwerinda',
      'logout': 'Vaamu',
    },
    'sw': {
      'app_name': 'FindiPro',
      'tagline': 'Pata watoa huduma wa kuaminika karibu nawe',
      'explore': 'Gundua',
      'categories': 'Makundi',
      'bookings': 'Uhifadhi',
      'messages': 'Ujumbe',
      'profile': 'Wasifu',
      'dashboard': 'Dashibodi',
      'search_hint': 'Tafuta mafundi bomba, umeme, kusafisha...',
      'find_services': 'Pata Huduma Zinazoaminika',
      'top_categories': 'Makundi Maarufu',
      'featured_providers': 'Wataalamu Walioidhinishwa',
      'see_all': 'Tazama yote',
      'view_profile': 'Tazama Wasifu',
      'book_now': 'Omba Huduma',
      'call_now': 'Piga Simu',
      'chat_now': 'Piga Gumzo',
      'select_language': 'Chagua Lugha',
      'change_language': 'Badilisha Lugha ya Programu',
      'lifetime_premium': 'Jaribio la Muda Mfupi',
      'verified_badge': 'Mtaalamu Aliyethibitishwa',
      'save': 'Hifadhi',
      'cancel': 'Ghairi',
      'apply': 'Tumia',
      'login': 'Ingia',
      'signup': 'Fungua Akaunti',
      'welcome_back': 'Karibu Tena',
      'become_provider': 'Kuwa Mtoa Huduma',
      'give_feedback': 'Toa Maoni & Ombi la Vipengele',
      'settings': 'Mipangilio',
      'rate_app': 'Kadiria & Toa Maoni',
      'privacy_policy': 'Sera ya Faragha & Masharti',
      'logout': 'Ondoka',
    },
    'fr': {
      'app_name': 'FindiPro',
      'tagline': 'Trouvez des professionnels de confiance près de chez vous',
      'explore': 'Explorer',
      'categories': 'Catégories',
      'bookings': 'Réservations',
      'messages': 'Messages',
      'profile': 'Profil',
      'dashboard': 'Tableau de bord',
      'search_hint': 'Rechercher plombiers, électriciens, nettoyage...',
      'find_services': 'Trouver des Services de Confiance',
      'top_categories': 'Catégories Populaires',
      'featured_providers': 'Professionnels Vérifiés',
      'see_all': 'Voir tout',
      'view_profile': 'Voir le Profil',
      'book_now': 'Réserver le Service',
      'call_now': 'Appeler',
      'chat_now': 'Discuter',
      'select_language': 'Choisir la langue',
      'change_language': 'Changer la langue de l\'application',
      'lifetime_premium': 'Essai Promotionnel Limité',
      'verified_badge': 'Pro Vérifié',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'apply': 'Appliquer',
      'login': 'Se Connecter',
      'signup': 'Créer un Compte',
      'welcome_back': 'Bon retour',
      'become_provider': 'Devenir Prestataire de Services',
      'give_feedback': 'Partager des Commentaires & Suggestions',
      'settings': 'Paramètres',
      'rate_app': 'Noter & Évaluer',
      'privacy_policy': 'Politique de Confidentialité',
      'logout': 'Se Déconnecter',
    },
    'es': {
      'app_name': 'FindiPro',
      'tagline': 'Encuentre profesionales de confianza cerca de usted',
      'explore': 'Explorar',
      'categories': 'Categorías',
      'bookings': 'Reservas',
      'messages': 'Mensajes',
      'profile': 'Perfil',
      'dashboard': 'Panel de Control',
      'search_hint': 'Buscar fontaneros, electricistas, limpieza...',
      'find_services': 'Encuentre Servicios Confiables',
      'top_categories': 'Categorías Populares',
      'featured_providers': 'Profesionales Verificados',
      'see_all': 'Ver todo',
      'view_profile': 'Ver Perfil',
      'book_now': 'Reservar Servicio',
      'call_now': 'Llamar',
      'chat_now': 'Chatear',
      'select_language': 'Seleccionar Idioma',
      'change_language': 'Cambiar Idioma de la Aplicación',
      'lifetime_premium': 'Prueba Promocional Limitada',
      'verified_badge': 'Profesional Verificado',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'apply': 'Aplicar',
      'login': 'Iniciar Sesión',
      'signup': 'Crear Cuenta',
      'welcome_back': 'Bienvenido de nuevo',
      'become_provider': 'Convertirse en Proveedor de Servicios',
      'give_feedback': 'Compartir Comentarios y Sugerencias',
      'settings': 'Ajustes',
      'rate_app': 'Calificar y Opinar',
      'privacy_policy': 'Política de Privacidad y Términos',
      'logout': 'Cerrar Sesión',
    },
    'ar': {
      'app_name': 'FindiPro',
      'tagline': 'اعثر على محترفين موثوقين بالقرب منك',
      'explore': 'استكشاف',
      'categories': 'الفئات',
      'bookings': 'الحجوزات',
      'messages': 'الرسائل',
      'profile': 'الملف الشخصي',
      'dashboard': 'لوحة التحكم',
      'search_hint': 'ابحث عن سباك، كهربائي، تنظيف...',
      'find_services': 'اعثر على خدمات موثوقة',
      'top_categories': 'الفئات الشائعة',
      'featured_providers': 'مقدمو خدمات موثوقون ومميزون',
      'see_all': 'عرض الكل',
      'view_profile': 'عرض الملف',
      'book_now': 'طلب خدمة',
      'call_now': 'اتصال',
      'chat_now': 'محادثة',
      'select_language': 'اختر اللغة',
      'change_language': 'تغيير لغة التطبيق',
      'lifetime_premium': 'تجربة ترويجية محدودة',
      'verified_badge': 'محترف موثق',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'apply': 'تطبيق',
      'login': 'تسجيل الدخول',
      'signup': 'إنشاء حساب جديد',
      'welcome_back': 'مرحباً بعودتك',
      'become_provider': 'انضم كمقدم خدمة',
      'give_feedback': 'مشاركة الملاحظات وطلب ميزات جديدة',
      'settings': 'الإعدادات',
      'rate_app': 'تقييم التطبيق',
      'privacy_policy': 'سياسة الخصوصية والشروط',
      'logout': 'تسجيل الخروج',
    },
  };

  static String get(String key, {String lang = 'en'}) {
    final langMap = _translations[lang] ?? _translations['en']!;
    return langMap[key] ?? _translations['en']?[key] ?? key;
  }
}

